<footer class="footer bg-dark">
  <div class="container pt-4 pt-md-5">
    <div class="row">
      <div class="col-sm-12 col-md-3  mb-3 text-left">

        <div class="">
          <a class="logo-brand" href="./">
            <img class="img-fluid logo-b" src="img/TigerSoft-footer.png"
              alt="Logo Tiger Soft, Chiclayo" />
          </a>
        </div>

          <ul class="social text-right">
            <li>
              <a class="icon-circle" href="" target="_blank" title="Facebook Tiger Soft" >
                <i class="bx bxl-facebook fs-1x-25"></i>
              </a>
            </li>
            <li>
              <a class="icon-circle"  href="" target="_blank"  title="Twitter Tiger Soft" >
                <i class='bx bxl-twitter fs-1x-25'></i>
              </a>
            </li>
            <li>
              <a class="icon-circle" href="" target="_blank" title="Youtube Tiger Soft">
                <i class='bx bx-caret-right fs-1x-25'></i>
              </a>
            </li>
          </ul>
        
         <!-- copy -->
        <div class="copy">
          <div class="col-12 text-center opacity-2  fs-x-14 text-white">
            <span class="text-primary">Tiger Soft © 2020</span> - Todos los derechos reservados <br>
          </div>
        </div>
        <div style="text-align: center;">
        <a class="powered-by" href="http://planeatec.com/" target="_blank" title="Planeatec Agencia de Marketing digital"
              alt="Planeatec Agencia de Marketing digital, Creado por planeatec">Creado por Planeatec - Gerson Oliva</a>
        </div>

      </div>

      <div class="col-sm-12 col-md-3 mb-3 ">
        <h5 class="text-primary fw-600">Enlaces</h5>
        <spam class="divider"></spam>
        <div class="media mb-3 mt-5">
          <ul class="media-body text-white text list-enlaces">
            <li><a href="./">Inicio</a></li>
            <li><a href="nosotros">Nosotros</a></li>
            <li><a href="servicios">Servicios</a></li>
            <li><a href="productos">Productos</a></li>
            <li><a href="contactanos">Contáctanos</a></li>
            <li><a href="#">Libro de Reclamaciones <i class='bx bx-book-open'></i></a></li>
            <li><a href="#">Politicas de Privacidad</a></li>
          </ul>
        </div>
        
        
      </div>

      <div class="col-sm-12 col-md-3 mb-3 ">

        <h5 class="text-primary fw-600">Llámanos</h5>
        <spam class="divider"></spam>
        <br><br>
        <div class="media-body text-white text">
            De Lunes a Domingo las 24 horas del día.
        </div>
        <h5 class="text-primary fw-600">(+51) 5587912</h5>
        <div class="media-body text-white text">
            <!-- Por WhatsApp, los domingos de 9:00am a 4:00pm. -->
            Por WhatsApp, atendemos  24 x 7 todos los días del año.
        </div>

        <div class="media mb-3 mt-4 ">
          <div class="media-body text-white-50 text_cel">
          <i class='bx bxl-whatsapp fs-2x-25' style="color: white; background: green; border-radius: 50%;"></i>
          <a class="link-white" href="https://api.whatsapp.com/send?phone=+51971257642" target="_blank">(+51) 971 257 642</a>
          </div>
        </div>

        <div class="media mb-3 mt-4 ">
          <div class="media-body text-white-50 text_cel">
          <i class='bx bxl-whatsapp fs-2x-25' style="color: white; background: green; border-radius: 60%;"></i>
          <a class="link-white" href="https://api.whatsapp.com/send?phone=+51943194233" target="_blank">(+51) 943 194 233</a>
          </div>
        </div>

      </div>

      <div class="col-sm-12 col-md-3 mb-3 ">

        <h5 class="text-primary fw-600">Descargar</h5>
        <spam class=" divider"></spam>

        <li class="nav-item ">
          <div class="google_play">
            <a class="nav-link text-md-center" href="https://play.google.com/store/apps/details?id=com.tigersoft.gps&hl=es" target="_blank">
              <span><img class="img-fluid" src="img/google_play.png"
              alt="Tiger Soft Google Play" /></span>
            </a>
          </div>
        </li>

      </div>

    </div>
  </div>

</footer>